#!/usr/bin/env sh

# 这里参考了 yabai 的 wiki 。具体步骤下面讲
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# 窗口布局 bsp: 平铺 float: 浮动
yabai -m config layout                       bsp
# 默认拆分规则 first_child second_child
yabai -m config window_placement             second_child
# 窗口间距设置
yabai -m config top_padding                  4
yabai -m config bottom_padding               4
yabai -m config left_padding                 4
yabai -m config right_padding                4
yabai -m config window_gap                   2
# 自动平衡所有窗口始终占据相同的空间
yabai -m config auto_balance                 off
# 如果禁用自动平衡，此项属性定义的是新窗口占用的空间量。0.5意为旧窗口占用50%
yabai -m config split_ratio                 0.50
# 鼠标修饰键 意思就是按着这个键就可以使用鼠标单独修改窗口大小了
yabai -m config mouse_modifier               fn
# fn + 左键 移动
yabai -m config mouse_action1                move
# fn + 右键 
yabai -m config mouse_action2                resize
# 焦点跟随鼠标 默认off: 关闭  autoraise:自动提升 autofocus: 自动对焦
yabai -m config focus_follows_mouse          autofocus
# 设置鼠标是否跟随当前活动窗口 默认 off: 关闭 on: 开启
yabai -m config mouse_follows_focus          on

# 浮动窗口问题在顶部
yabai -m config window_topmost               on
# 修改窗口阴影 on: 打开 off: 关闭 float: 只显示浮动窗口的阴影
yabai -m config window_shadow                float

# 窗口透明度设置
yabai -m config window_opacity               off
# 配置活动窗口不透明度
# yabai -m config active_window_opacity        1.0             
# yabai -m config normal_window_opacity        0.9
# yabai -m config window_opacity_duration      0.0

# 在主显示器上的每个空间顶部添加 20 填充 底部添加 0 填充
# yabai -m config external_bar main:20:0
# 在所有显示器上的每个空间顶部添加 0 填充 底部添加 0 填充
yabai -m config external_bar all:0:0

# ================================ 规则 ================================
# 打开系统偏好设置，不使用平铺模式
yabai -m rule --add app="^系统偏好设置$" manage=off
yabai -m rule --add app="^提醒事项$" manage=off
yabai -m rule --add app="^关于本机$" manage=off
otherApp='^(阿里钉|阿里郎|App Store|IINA|Xnip|Calendar|日历|System Preferences|系统偏好设置|Mail|微信|WeChatc|QQ|印象笔记|灵犀|网易云音乐|Alfred Preferences|Tencent Lemon|企业微信|Todoist|Input Source Pro|Spotify)$'

yabai -m rule --add app="${otherApp}" manage=off
yabai -m rule --add app="^(Google Chrome|Microsoft Edge)$" role="AXWindow" subrole="AXStandardWindow" manage=on layer=below

JetBrainsApp='^(IntelliJ IDEA|WebStorm|GoLand|Pycharm)$'
yabai -m rule --add app="${JetBrainsApp}" manage=off
yabai -m rule --add app="${JetBrainsApp}" title=".*\[(.*)\].*" manage=on

yabai -m config window_border                on
yabai -m config window_border_placement      inset
yabai -m config window_border_width          3
yabai -m config window_border_radius         12
yabai -m config active_window_border_topmost off
yabai -m config active_window_border_color   0xfc11ee69
yabai -m config normal_window_border_color   0x00ffffff
yabai -m config insert_feedback_color   0xffd75f5f


echo "yabai configuration loaded.."


